name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push API
        run: |
          docker build -t netaaviv100/api-service ./api-service
          docker push netaaviv100/api-service

      - name: Build & Push Worker
        run: |
          docker build -t netaaviv100/worker-service ./worker-service
          docker push netaaviv100/worker-service

